// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhzqtqierthyuznwbjoc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1oenF0cWllcnRoeXV6bndiam9jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMjQzNDQsImV4cCI6MjA2NjYwMDM0NH0.7a85hGuAj4_QyGPqkdrZBNT94MckCk3MsnOpdxyZD5U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);